- build.gradle
- layer-api/src/main/java/org/layer/config/AuthValueConfig.java
- layer-api/src/main/java/org/layer/config/SwaggerConfig.java
- layer-api/src/main/java/org/layer/domain/jwt/JwtAuthenticationFilter.java
- layer-api/src/main/java/org/layer/domain/space/api/SpaceApi.java
- layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
- layer-api/src/main/java/org/layer/domain/space/dto/SpaceRequest.java
- layer-api/src/main/java/org/layer/domain/space/dto/SpaceResponse.java
- layer-api/src/main/java/org/layer/domain/space/exception/SpaceExceptionType.java
- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- layer-common/src/main/java/org/layer/common/annotation/AtLeastNotNull.java
- layer-common/src/main/java/org/layer/common/exception/GlobalExceptionHandler.java
- layer-common/src/main/java/org/layer/common/exception/ValidationCustomException.java
- layer-common/src/main/java/org/layer/common/validator/AtLeastNotNullValidator.java
- layer-domain/src/main/java/org/layer/domain/BaseEntity.java
- layer-domain/src/main/java/org/layer/domain/space/dto/SpaceWithMemberCount.java
- layer-domain/src/main/java/org/layer/domain/space/entity/MemberSpaceRelation.java
- layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
- layer-domain/src/main/java/org/layer/domain/space/repository/MemberSpaceRelationRepository.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceCustomRepository.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepository.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
- QueryDSL 적용
- Swagger Bearer Auth 적용
- feat/#LS-19
- closed #
> feat: 스페이스 단건조회 / LS-13 리뷰 사항 적용

- build.gradle
- layer-api/src/main/java/org/layer/domain/space/api/SpaceApi.java
- layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
- layer-api/src/main/java/org/layer/domain/space/dto/SpaceResponse.java
- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- layer-domain/src/main/java/org/layer/domain/space/dto/SpaceWithMemberCount.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
- Retrospect API의 회원 수 조회 기능을 Space API로 이전했어요.
- 기존 회원수 조회 API에서 잘못된 결과를 반환하고 있었어요.
- 성능 최적화가 필요한 부분을 최적화 했어요.
- 현재 `layer`의 사용자는 `Member`로 부르고 있기 때문에 `userCount`라는 명칭을 `memberCount`로 변경했어요.
```cURL
curl -X 'GET' \
'http://api.layerapp.io/api/auth/oauth2/kakao?code=bIq7a17tSqQjKiOJivxwLXV8HY486xh1533tEpeRjwjgMwHTmEWWNAAAAAQKPCPoAAABkKzDGRbo6jj-qNQmaA' \
-H 'accept: */*'
```
```json
{
"data": [
{
"id": 7,
"category": "TEAM",
"field": "DESIGN",
"name": "이름",
"introduction": "string",
"formId": null,
"memberCount": 2
},
{
"id": 8,
"category": "INDIVIDUAL",
"field": "DESIGN",
"name": "string",
"introduction": "string",
"formId": null,
"memberCount": 1
}
],
"meta": {
"hasNextPage": true,
"cursor": 8
}
}
```
- feat/LS-23 -> develop
- closed #
> feat/Ls-23: 스페이스 회원 조회 API

- layer-api/src/main/java/org/layer/domain/space/api/SpaceApi.java
- layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
- layer-api/src/main/java/org/layer/domain/space/exception/SpaceExceptionType.java
- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
- 스페이스 초대 링크를 통해 페이지에 진입 시 호출할 API를 추가했어요.
- 명칭을 `초대하기` 라고 하였지만 사실 `입장하기` 가 더 맞는 표현인 것 같아요
- 내가 속한 스페이스 떠나기 API를 추가했어요.
`스페이스 떠나기`  관련하여 논의가 필요하다 판단된 부분에 주석 달아뒀어요!
해당 주석 내용 공유드립니다.
```
개인 스페이스의 경우, 이탈 시 Space 엔티티의 로직이 된다.
따라서 INDIVIDUAL인 Space인 경우 가능한 케이스는 2가지로
1. Space 삭제
2. 속한 스페이스 떠나기, 스페이스 삭제하기 분리
현재는 2번 케이스를 기준으로 구현되어 있음
```
- feat/LS-25 -> develop
- closed #
> Feat/lS-25 : 스페이스 초대하기/떠나기 API

- layer-api/src/main/java/org/layer/domain/question/controller/QuestionApi.java
- layer-api/src/main/java/org/layer/domain/question/controller/QuestionController.java
- layer-api/src/main/java/org/layer/domain/question/controller/dto/response/QuestionGetResponse.java
- layer-api/src/main/java/org/layer/domain/question/controller/dto/response/QuestionListGetResponse.java
- layer-api/src/main/java/org/layer/domain/question/service/QuestionService.java
- layer-api/src/main/java/org/layer/domain/question/service/dto/response/QuestionGetServiceResponse.java
- layer-api/src/main/java/org/layer/domain/question/service/dto/response/QuestionListGetServiceResponse.java
- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- layer-common/src/main/java/org/layer/common/exception/RetrospectExceptionType.java
- layer-domain/src/main/java/org/layer/domain/question/entity/Question.java
- layer-domain/src/main/java/org/layer/domain/question/repository/QuestionRepository.java
- layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
- layer-domain/src/main/java/org/layer/domain/retrospect/exception/RetrospectException.java
- layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectRepository.java
- 엔티티 변경이 있었습니다. 커밋보고 의견주시면 감사하겠습니다!
- 그 외는 특이사항 없었습니다!
- feat/#LS-24
- closed #
> feat/LS-24: 특정 회고 질문 목록 조회 구현

- build.gradle
- layer-api/src/main/java/org/layer/LayerApplication.java
- layer-api/src/main/java/org/layer/config/SecurityConfig.java
- layer-api/src/main/java/org/layer/domain/external/api/ExternalApi.java
- layer-api/src/main/java/org/layer/domain/external/controller/ExternalController.java
- layer-api/src/main/java/org/layer/domain/external/dto/ExternalRequest.java
- layer-api/src/main/java/org/layer/domain/external/dto/ExternalResponse.java
- layer-api/src/main/java/org/layer/domain/space/api/SpaceApi.java
- layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
- layer-api/src/main/java/org/layer/domain/space/dto/SpaceRequest.java
- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- layer-common/src/main/java/org/layer/common/exception/ExternalExceptionType.java
- layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceCustomRepository.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
- layer-external/src/main/java/org/layer/external/ncp/config/NcpConfig.java
- layer-external/src/main/java/org/layer/external/ncp/enums/ImageDomain.java
- layer-external/src/main/java/org/layer/external/ncp/exception/ExternalExeption.java
- layer-external/src/main/java/org/layer/external/ncp/service/NcpService.java
- pre-signed-url 기반 이미지 업로드 기능을 구현했어요.
- S3 SDK를 통해 ncp bucket과 연동했어요
- ncp 연결을 위한 환경변수가 추가됬어요. 수정부분 포함 노션에 최신화 완료했습니다
- 이미지 업로드 url 요청 결과
- feat/LS-33 -> develop
- closed #
> feat/LS-33: 이미지 업로드 API 구현하기

- layer-api/src/main/java/org/layer/LayerApplication.java
- layer-api/src/main/java/org/layer/domain/answer/controller/dto/request/AnswerCreateRequest.java
- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- layer-api/src/main/java/org/layer/domain/question/controller/QuestionController.java
- layer-api/src/main/java/org/layer/domain/question/controller/dto/response/QuestionGetResponse.java
- layer-api/src/main/java/org/layer/domain/question/service/QuestionService.java
- layer-api/src/main/java/org/layer/domain/question/service/dto/response/QuestionGetServiceResponse.java
- layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectController.java
- layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/RetrospectCreateRequest.java
- layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/response/RetrospectGetResponse.java
- layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/response/RetrospectListGetResponse.java
- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- layer-api/src/main/java/org/layer/domain/retrospect/service/dto/response/RetrospectGetServiceResponse.java
- layer-common/src/main/java/org/layer/common/exception/RetrospectExceptionType.java
- layer-domain/src/main/java/org/layer/domain/common/time/RealTime.java
- layer-domain/src/main/java/org/layer/domain/common/time/Time.java
- layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
- layer-domain/src/main/java/org/layer/domain/space/repository/MemberSpaceRelationRepository.java
- 여러 API 들을 뷰에 맞게 수정했습니다.
- 의존성 역전을 사용해서 의존성을 최소화시켰습니다.
- 나중에 테스트 코드 작성할 때도 매우 유용하기에 이렇게 구현했습니다.
- feat/
- closed #
> chore/LS-35 : 여러 API 뷰에 맞게 수정

- layer-api/src/main/java/org/layer/domain/external/api/ExternalApi.java
- layer-api/src/main/java/org/layer/domain/external/controller/ExternalController.java
- layer-api/src/main/java/org/layer/domain/external/dto/ExternalResponse.java
- layer-external/src/main/java/org/layer/external/ncp/dto/NcpResponse.java
- layer-external/src/main/java/org/layer/external/ncp/service/NcpService.java
presigned URL 요청 시 저장 성공 이후 object 요청 주소가 함께 전달됩니다.
- closed #49
> feat: presigned URL 이미지 저장 로직 변경

- layer-api/src/main/java/org/layer/domain/auth/service/AuthService.java
- layer-api/src/main/java/org/layer/domain/member/service/MemberService.java
- layer-common/src/main/java/org/layer/common/exception/MemberExceptionType.java
유저가 처음 로그인해서 회원가입이 필요한 상황에서
응답 코드와 메시지를 아래 사진처럼 수정했습니다.
수정된 내용:
기존 응답 내용:
- fix/53 -> develop
- closed #53
> fix: 회원 가입이 필요한 상황에서의 응답 내용 수정

- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- layer-api/src/main/java/org/layer/domain/form/controller/FormApi.java
- layer-api/src/main/java/org/layer/domain/form/controller/FormController.java
- layer-api/src/main/java/org/layer/domain/form/controller/dto/response/DefaultFormGetResponse.java
- layer-api/src/main/java/org/layer/domain/form/controller/dto/response/DefaultQuestionGetResponse.java
- layer-api/src/main/java/org/layer/domain/form/service/FormService.java
- layer-api/src/main/java/org/layer/domain/question/service/QuestionService.java
- layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/QuestionCreateRequest.java
- layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/RetrospectCreateRequest.java
- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- layer-common/src/main/java/org/layer/common/exception/FormExceptionType.java
- layer-common/src/main/java/org/layer/common/exception/SpaceExceptionType.java
- layer-domain/src/main/java/org/layer/domain/actionItem/entity/ActionItem.java
- layer-domain/src/main/java/org/layer/domain/form/entity/Form.java
- layer-domain/src/main/java/org/layer/domain/form/entity/FormType.java
- layer-domain/src/main/java/org/layer/domain/form/exception/FormException.java
- layer-domain/src/main/java/org/layer/domain/form/repository/FormRepository.java
- layer-domain/src/main/java/org/layer/domain/question/entity/Question.java
- layer-domain/src/main/java/org/layer/domain/question/repository/QuestionRepository.java
- layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
* [수정] 회고 생성 API : 새로 템플릿 만드는 경우에 대한 값 추가, 새로 만드는 경우 로직 추가
* [새로 구현] 특정 스페이스의 기본 회고폼 조회 API
- 변경된 테이블 설계안
* 에러발생 -> 정상동작
- feat/#51 -> dev
- closed #51
> feat : 질문 수정 관련 로직 구현

- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
- 조회시 npe 발생하는 에러를 해결했습니다.
- feat/#84 -> dev
- closed #84
> fix: 회고 임시 저장 조회 로직 npe 오류 해결

- layer-api/src/main/java/org/layer/domain/member/controller/MemberApi.java
- layer-api/src/main/java/org/layer/domain/member/controller/MemberController.java
- layer-api/src/main/java/org/layer/domain/member/controller/dto/UpdateMemberInfoRequest.java
- layer-api/src/main/java/org/layer/domain/member/controller/dto/UpdateMemberInfoResponse.java
- layer-api/src/main/java/org/layer/domain/member/service/MemberService.java
- layer-domain/src/main/java/org/layer/domain/form/enums/FormPublishedBy.java
- layer-domain/src/main/java/org/layer/domain/member/entity/Member.java
- layer-domain/src/main/java/org/layer/domain/member/repository/MemberRepository.java
- 회원의 이름, 프로필 사진을 변경하는 API를 작성했습니다.
- feat/98
- closed #98
> feat: 멤버 정보 변경 API 작성

- layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectController.java
- layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/response/RetrospectGetResponse.java
- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- layer-api/src/main/java/org/layer/domain/retrospect/service/dto/response/RetrospectGetServiceResponse.java
회고 조회 시 생성일자와 종료일자를 응답하도록 수정했어요.
- feat/
- closed #
> feat: 회고 조회 응답 필드 추가하기 (#105)

- layer-api/src/main/java/org/layer/domain/form/controller/FormApi.java
- layer-api/src/main/java/org/layer/domain/form/controller/FormController.java
- layer-api/src/main/java/org/layer/domain/form/controller/dto/response/CustomTemplateListResponse.java
- layer-api/src/main/java/org/layer/domain/form/controller/dto/response/CustomTemplateResponse.java
- layer-api/src/main/java/org/layer/domain/form/service/FormService.java
- layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/QuestionCreateRequest.java
- layer-common/src/main/java/org/layer/common/exception/FormExceptionType.java
- layer-domain/src/main/java/org/layer/domain/form/repository/FormRepository.java
- 특정 스페이스에 속한 커스텀 폼 목록을 최신순으로 불러오는 api를 작성했습니다.
```sql
Hibernate: 
select
msr1_0.id,
msr1_0.created_at,
msr1_0.member_id,
msr1_0.space_id,
msr1_0.updated_at 
from
where
msr1_0.space_id=? 
and msr1_0.member_id=?
Hibernate: 
select
f1_0.id,
f1_0.created_at,
f1_0.form_tag,
f1_0.form_type,
f1_0.introduction,
f1_0.member_id,
f1_0.space_id,
f1_0.title,
f1_0.updated_at 
from
form f1_0 
where
f1_0.form_type=? 
order by
f1_0.id desc 
limit
?, ?
Hibernate: 
select
count(f1_0.id) 
from
form f1_0 
where
f1_0.form_type=?
```
- feat/103
- closed #103
> feat: 스페이스에 속한 커스텀 폼 목록 조회

- layer-api/src/main/java/org/layer/domain/space/controller/SpaceApi.java
- layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
- layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceResponse.java
- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- layer-domain/src/main/java/org/layer/domain/space/dto/SpaceMember.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceCustomRepository.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
스페이스 팀원 목록 조회하기 API를 추가했어요.
팀장, 스페이스 가입이 빠른순으로 정렬되어 응답합니다.
```
select
m1_0.id,
m1_0.profile_image_url,
m1_0.name,
s1_0.leader_id=m1_0.id 
from
left join
member m1_0 
on msr1_0.member_id=m1_0.id 
left join
space s1_0 
on msr1_0.space_id=s1_0.id 
where
msr1_0.space_id=? 
order by
msr1_0.created_at
```
- feat/
- closed #
> feat:스페이스 팀원 목록 조회하기 (#107)

- layer-api/src/main/java/org/layer/domain/form/controller/dto/request/RecommendFormQueryDto.java
- layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectApi.java
- layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectController.java
- layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/RetrospectUpdateRequest.java
- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- layer-common/src/main/java/org/layer/common/exception/RetrospectExceptionType.java
- layer-domain/src/main/java/org/layer/domain/form/enums/RetrospectPeriodic.java
- layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
- layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
- 회고 수정 및 삭제 API 구현했습니다.
- feat/#117 -> dev
- closed #117
> feat: 회고 수정 및 삭제 로직 구현

- layer-api/src/main/java/org/layer/domain/form/controller/dto/response/CustomTemplateResponse.java
- layer-api/src/main/java/org/layer/domain/form/service/FormService.java
> fix: 스페이스 커스텀 폼 조회 응답에 폼아이디 추가

- layer-api/src/main/java/org/layer/domain/form/service/FormService.java
- layer-api/src/main/resources/application-dev.yml
- layer-domain/src/main/java/org/layer/domain/form/repository/FormRepository.java
스페이스에 속한 커스텀 폼 리스트를 뽑아오는 API의 응답 값이 좀 이상해서 다시 봤더니,
스페이스에 속한 커스텀 폼을 가져와야하는데, 그냥 모든 커스텀 폼을 가져오고 있었더라고요...
해당 부분을 수정했습니다.
수정 전 FormService.java
```
Page<Form> customFormList = formRepository.findAllByFormTypeOrderByIdDesc(pageable, CUSTOM, spaceId);
```
수정 후 FormService.java
```
Page<Form> customFormList = formRepository.findAllByFormTypeAndSpaceIdOrderByIdDesc(pageable, CUSTOM, spaceId);
```
- fix/127
- closed #127
> fix: 스페이스 커스텀 폼 조회 로직 수정

- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- layer-domain/src/main/java/org/layer/domain/actionItem/repository/ActionItemRepository.java
- layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectRepository.java
스페이스 삭제시 진행중/완료 회고 삭제와 연계된 액션아이템을 삭제하는 기능을 추가했습니다
```SQL
Hibernate: 
select
s1_0.id,
s1_0.banner_url,
s1_0.category,
s1_0.form_id,
s1_0.leader_id,
s1_0.name,
s1_0.updated_at 
from
space s1_0 
where
s1_0.id=?
Hibernate: 
delete 
from
action_item ai1_0 
where
ai1_0.space_id=?
Hibernate: 
delete 
from
retrospect r1_0 
where
r1_0.space_id=?
Hibernate: 
delete 
from
where
msr1_0.space_id=?
Hibernate: 
select
s1_0.id,
s1_0.banner_url,
s1_0.category,
s1_0.form_id,
s1_0.leader_id,
s1_0.name,
s1_0.updated_at 
from
space s1_0 
where
s1_0.id=?
Hibernate: 
delete 
from
space 
where
id=?
```
- feat/#130
- closed #130
> fix: 스페이스 삭제시 회고와 액션아이템 삭제

- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- 수정했을 때도, 임시저장이 가능해져야 해서 수정했습니다!
- 이제부터는 회고작성 후에도, 임시저장이 가능해집니다.
- feat/#134 -> dev
- closed #134
> chore: 임시저장 예외케이스 수정

- layer-api/src/main/java/org/layer/domain/auth/controller/AuthApi.java
- layer-api/src/main/java/org/layer/domain/auth/controller/dto/MemberInfoResponse.java
- layer-api/src/main/resources/application-dev.yml
GET `/api/auth/member-info` api의 응답값에 회원 프로필 사진 링크를 추가했습니다
- feat/
- closed #140
> fix: 회원 정보 조회 응답 imageUrl 추가

- layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceResponse.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
- 스페이스 조회 시 생성일자 기준으로 내림차순 정렬을 적용했어요.
```
Hibernate: 
select
s1_0.id,
s1_0.updated_at,
s1_0.category,
s1_0.name,
s1_0.leader_id,
s1_0.form_id,
count(msr2_0.space_id),
s1_0.banner_url 
from
space s1_0 
left join
on s1_0.id=msr1_0.space_id 
left join
member_space_relation msr2_0 
on s1_0.id=msr2_0.space_id 
left join
form f1_0 
on s1_0.form_id=f1_0.space_id 
where
msr1_0.member_id=? 
and s1_0.id>? 
group by
s1_0.id 
order by
s1_0.created_at desc 
limit
?
```
- feat/
- closed #
> fix: 스페이스 정렬 순서 변경하기

- layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceResponse.java
- 스페이스 단건조회 리더 아이디 반환하기
```
Hibernate: 
select
s1_0.id,
s1_0.updated_at,
s1_0.category,
s1_0.name,
s1_0.leader_id,
s1_0.form_id,
count(msr2_0.space_id),
s1_0.banner_url 
from
space s1_0 
left join
on s1_0.id=msr1_0.space_id 
left join
member_space_relation msr2_0 
on s1_0.id=msr2_0.space_id 
left join
form f1_0 
on s1_0.form_id=f1_0.space_id 
where
s1_0.id=? 
and msr1_0.member_id=?
[2024-08-16 19:04:32:51333] [http-nio-8080-exec-7] INFO  [org.layer.aop.ExecutionLoggingAop.logExecutionTrace:76] - [ExecutionTime] SpaceController.getSpaceById --> 17 (ms)
```
- feat/
- closed #
> feat: 스페이스 단건조회 리더 아이디 반환하기

- layer-api/src/main/java/org/layer/domain/template/controller/dto/TemplateDetailInfoResponse.java
- layer-api/src/main/java/org/layer/domain/template/controller/dto/TemplatePurposeResponse.java
- layer-api/src/main/java/org/layer/domain/template/service/TemplateService.java
- layer-domain/src/main/java/org/layer/domain/template/entity/TemplatePurpose.java
- layer-domain/src/main/java/org/layer/domain/template/repository/TemplatePurposeRepository.java
- 기본 템플릿 조회 시 목적 태그(TemplatePurpose) 목록 응답하기
- feat/
- closed #153
> feat: 기본 템플릿 조회 시 목적 태그 목록 응답하기

- .gitignore
- build.gradle
- layer-api/infra/development/docker-compose.yaml
- layer-api/src/main/java/org/layer/domain/auth/controller/AuthApi.java
- layer-api/src/main/java/org/layer/domain/auth/controller/AuthController.java
- layer-api/src/main/java/org/layer/domain/auth/service/AuthService.java
- layer-api/src/main/java/org/layer/domain/member/controller/MemberApi.java
- layer-api/src/main/java/org/layer/domain/member/controller/MemberController.java
- layer-api/src/main/java/org/layer/domain/member/controller/dto/CreateFeedbackRequest.java
- layer-api/src/main/java/org/layer/domain/member/controller/dto/WithrawMemberRequest.java
- layer-api/src/main/java/org/layer/domain/member/service/MemberService.java
- layer-api/src/main/resources/application-dev.yml
- layer-api/src/main/resources/application-local.yml
- layer-api/src/main/resources/application-prod.yml
- layer-api/src/main/resources/application-test.yml
- layer-api/src/test/java/org/layer/domain/retrospect/service/RetrospectServiceTest.java
- layer-domain/src/main/java/org/layer/domain/member/entity/Member.java
- layer-domain/src/main/java/org/layer/domain/member/entity/MemberFeedback.java
- layer-domain/src/main/java/org/layer/domain/member/repository/MemberCustomRepository.java
- layer-domain/src/main/java/org/layer/domain/member/repository/MemberRepository.java
- layer-domain/src/main/java/org/layer/domain/member/repository/MemberRepositoryImpl.java
- layer-external/src/main/java/org/layer/external/google/config/GoogleConfig.java
- layer-external/src/main/java/org/layer/external/google/enums/SheetType.java
- layer-external/src/main/java/org/layer/external/google/service/GoogleApiService.java
- 사용성 피드백 정보, 회원탈퇴 인사이트 작성 시 구글 시트에 행이 추가됩니다.
- 각 카테고리는 Sheet를 기준으로 저장됩니다.
- feat/
- closed #151
> feat: 구글 시트 API를 활용한 사용자 설문 CRM 연동하기

- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- 스페이스 떠니기 API에 팀장이 아닐경우 throw하던 로직을 팀장일 경우로 변경했어요.
- feat/
- closed #
> fix: 스페이스 떠나기 팀장확인 로직 변경

- layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceResponse.java
- layer-domain/src/main/java/org/layer/domain/space/dto/Leader.java
- layer-domain/src/main/java/org/layer/domain/space/dto/SpaceWithMemberCount.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
- 스페이스 조회 시 리더 정보를 포함하여 응답합니다
```
Hibernate: 
select
s1_0.id,
s1_0.updated_at,
s1_0.category,
s1_0.name,
m1_0.id,
m1_0.created_at,
m1_0.email,
m1_0.member_role,
m1_0.name,
m1_0.profile_image_url,
m1_0.social_id,
m1_0.social_type,
m1_0.updated_at,
s1_0.form_id,
count(msr2_0.space_id),
s1_0.banner_url 
from
space s1_0 
left join
on s1_0.id=msr1_0.space_id 
left join
member_space_relation msr2_0 
on s1_0.id=msr2_0.space_id 
left join
member m1_0 
on s1_0.leader_id=m1_0.id 
left join
form f1_0 
on s1_0.form_id=f1_0.space_id 
where
msr1_0.member_id=? 
group by
s1_0.id,
s1_0.updated_at,
s1_0.category,
s1_0.name,
m1_0.id,
s1_0.form_id,
s1_0.banner_url
```
- …
> fix: 스페이스 조회시 리더 정보 응답하기 #157

- layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/AnswerListGetResponse.java
- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- layer-api/src/main/java/org/layer/domain/form/service/FormService.java
- layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/response/RetrospectGetResponse.java
- 필수 질문에 대한 처리 진행
- 분석 데이터를 생성 여부 `회고 분석 조회 API` 에 추가
- 필수 질문에 대한 개념을 서버에서 제대로 구현하지 않았던 것 같습니다!
- 하지만 뭔가 느낌상 `(답변이 일반텍스트가 아닌 다른 입력 && 필수질문이 아님)` 의 조건은 먼 얘기인 것 같다는 생각이 들었습니다,,,ㅎㅎ,, 그래서 살짝은 야매이긴 하지만 현재 정책에는 잘 맞지 않을까 해서 구현했는데요! 다른 의견 있으시면 편하게 말씀주세용!!
- 해당 데이터는 분석 테이블 한 번 조회하는 걸로 구현했습니다.
`ASIS`
`TOBE`
생략
- feat/
- closed #149
> chore: fe 요청에 맞게 수정

- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- 회의 내용 바탕으로 수정했습니다.
수정된 로직은 이곳 입니다!
- feat/#176 -> dev
- closed #176
> chore: 회고 생성 API 수정

- layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectApi.java
- layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectController.java
- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- layer-common/src/main/java/org/layer/common/exception/RetrospectExceptionType.java
- layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
- layer-domain/src/main/java/org/layer/domain/space/entity/Team.java
- 회고 마감 API 를 구현했습니다.
- feat/#185
- closed #185
> feat: 회고 마감 API 구현

- layer-api/src/main/java/org/layer/domain/analyze/service/AnalyzeService.java
- 회고 분석 팀원도 조회가능하도록 변경했습니다.
- feat/
- closed #187
> fix: 회고 분석 팀원도 조회 가능하도록 변경

- layer-api/src/main/java/org/layer/config/SecurityConfig.java
- layer-api/src/main/java/org/layer/domain/admin/controller/AdminApi.java
- layer-api/src/main/java/org/layer/domain/admin/controller/AdminController.java
- layer-api/src/main/java/org/layer/domain/admin/controller/dto/AdminRetrospectsGetResponse.java
- layer-api/src/main/java/org/layer/domain/admin/controller/dto/AdminSpacesGetResponse.java
- layer-api/src/main/java/org/layer/domain/admin/service/AdminService.java
- layer-api/src/main/resources/application-dev.yml
- layer-api/src/main/resources/application-local.yml
- layer-api/src/main/resources/application-prod.yml
- layer-api/src/main/resources/application-test.yml
- layer-domain/src/main/java/org/layer/domain/retrospect/dto/AdminRetrospectGetResponse.java
- layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectAdminRepository.java
- layer-domain/src/main/java/org/layer/domain/space/dto/AdminSpaceGetResponse.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceAdminRepository.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepository.java
- admin API를 개발했습니다.
- feat/#205 -> dev
- closed #205
> feat: admin API 개발

- layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/RetrospectCreateRequest.java
- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
- 회고 마감일을 nullable 하게 수정했습니다.
- feat/
- closed #215
> chore: 회고 마감일 nullable 하게 수정

- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
- 회고 답변 직후에 응답 확인할 수 있도록 수정했습니다.
- feat/
- closed #236
> chore: 회고 답변 직후에 응답 확인할 수 있도록 수정

- layer-domain/src/main/java/org/layer/domain/member/entity/Member.java
중복 요청으로 인한 중복 회원가입을 방지하기 위해 social_id, social_type에 복합 유니크 제약조건을 걸었습니다.
운영 DB에도 alter문으로 유니크 조건 추가했습니다!
+DB 보니까 social_id 중복으로 된 회원은 없어서 아직 실제로 중복 회원가입이 된 것 같지는 않습니다!
h2 DB에 ddl-auto: create으로 실행했을 때 발생한 쿼리
운영 DB에 `show create table member` 했을 때, 유니크 조건 추가된 것 캡처
- feat/
- closed #
> fix: Table 어노테이션으로 복합 유니크 제약조건 추가

- layer-api/src/main/java/org/layer/domain/answer/controller/AnswerController.java
- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- layer-api/src/main/resources/application-test.yml
- layer-api/src/main/resources/console-appender.xml
- layer-api/src/main/resources/logback-spring.xml
- layer-api/src/test/java/org/layer/LayerApplicationTests.java
- layer-api/src/test/java/org/layer/domain/answer/service/AnswerServiceTest.java
- layer-api/src/test/java/org/layer/domain/retrospect/service/RetrospectServiceTest.java
- layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
- layer-domain/src/test/java/layer/domain/retrospect/entity/RetrospectTest.java
- 예전에는 조금 엄격하게 구현했었는데요! 회고 완료 후에 새로운 멤버가 들어와도 완료된 회고를 볼 수 있도록 기능을 수정했습니다.
- 검증 로직을 아예 제거했습니다.
- feat/
- closed #
> fix: 특정 회고의 답변을 완료하지 않아도 완료된 회고를 볼 수 있도록 수정

- layer-domain/src/main/java/org/layer/domain/analyze/entity/AnalyzeDetail.java
- rank 가 예약어라 배치 서버가 제대로 돌아가지 않는 문제가 있습니다.
- 예전에는 어떻게 잘 돌아갔는지 의문입니다...
- feat/
- closed #283
> fix: 엔티티 예약어로 인한 컬럼 수정

- layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceRequest.java
- layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceResponse.java
- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- layer-api/src/main/java/org/layer/global/exception/ApiSpaceExceptionType.java
- layer-api/src/test/java/org/layer/domain/fixture/FormFixture.java
- layer-api/src/test/java/org/layer/domain/fixture/MemberFixture.java
- layer-api/src/test/java/org/layer/domain/fixture/MemberSpaceRelationFixture.java
- layer-api/src/test/java/org/layer/domain/fixture/SpaceFixture.java
- layer-api/src/test/java/org/layer/domain/space/SpaceServiceTest.java
- layer-domain/src/main/java/org/layer/domain/form/entity/Form.java
- layer-domain/src/main/java/org/layer/domain/space/dto/Leader.java
- layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
- layer-domain/src/main/java/org/layer/domain/space/repository/MemberSpaceRelationRepository.java
- layer-external/src/main/java/org/layer/storage/service/StorageService.java
- 스페이스 단건 조회 로직을 리팩토링했습니다.
- 기존 쿼리는 보기가 다소 불편하다고 생각했습니다. N번 join 중첩이 있어 이를 개선하기 위해 쿼리를 분리하여 구현했습니다.
- 추가적으로 테스트 코드도 작성했습니다.
- feat/
- closed #317
> refactor: 스페이스 단건 조회 리팩토링

- .github/workflows/aws-cicd-dev.yml
- layer-api/src/main/java/org/layer/admin/aop/MemberActivityAspect.java
- layer-api/src/main/java/org/layer/admin/cache/MemberActivityCache.java
- layer-api/src/main/java/org/layer/admin/member/controller/AdminMemberApi.java
- layer-api/src/main/java/org/layer/admin/member/controller/AdminMemberController.java
- layer-api/src/main/java/org/layer/admin/member/controller/dto/GetMemberActivityResponse.java
- layer-api/src/main/java/org/layer/admin/member/controller/dto/GetMembersActivitiesResponse.java
- layer-api/src/main/java/org/layer/admin/member/service/AdminMemberService.java
- layer-api/src/main/java/org/layer/admin/retrospect/controller/AdminRetrospectApi.java
- layer-api/src/main/java/org/layer/admin/retrospect/controller/AdminRetrospectController.java
- layer-api/src/main/java/org/layer/admin/retrospect/controller/dto/AdminRetrospectCountGetResponse.java
- layer-api/src/main/java/org/layer/admin/retrospect/controller/dto/AdminRetrospectsGetResponse.java
- layer-api/src/main/java/org/layer/admin/retrospect/service/AdminRetrospectService.java
- layer-api/src/main/java/org/layer/admin/space/controller/AdminSpaceApi.java
- layer-api/src/main/java/org/layer/admin/space/controller/AdminSpaceController.java
- layer-api/src/main/java/org/layer/admin/space/controller/dto/AdminSpaceCountGetResponse.java
- layer-api/src/main/java/org/layer/admin/space/controller/dto/AdminSpacesGetResponse.java
- layer-api/src/main/java/org/layer/admin/space/service/AdminSpaceService.java
- layer-api/src/main/java/org/layer/domain/admin/cache/MemberActivityCache.java
- layer-api/src/main/java/org/layer/scheduler/MemberActivityScheduler.java
- layer-api/src/main/resources/application-dev.yml
- layer-api/src/main/resources/application-local.yml
- layer-api/src/main/resources/application-prod.yml
- layer-api/src/main/resources/application-test.yml
- layer-external/src/main/java/org/layer/discord/DiscordAppender.java
- layer-external/src/main/java/org/layer/discord/event/MemberActivityEvent.java
- layer-external/src/main/java/org/layer/discord/event/MemberActivityEventListener.java
- layer-external/src/main/java/org/layer/discord/infra/DiscordWebhookMemberActivityClient.java
- 활성 유저에 대한 정보가 있으면 다음 기능에 큰 도움이 될 것 같아 구현해봤습니다.
- 매일 데이터가 초기화되기 때문에 간단하게 로컬캐시로 구현해봤습니다. 테스트 용도이기에 팀원분들의 의견을 받아보고 추후에 redis나 DB 사용을 고민해보겠습니다!
- 기존 서비스 로직의 수정을 최소화하기 위해 AOP 로 구현했습니다.
-🚨 yml 설정파일도 수정해야 합니다 !
- 결과는 디스코드 참고해주시면 될 것 같습니다 !
- feat/
- closed #331
> feat: 활성 유저 집계 기능 구현

- layer-api/src/main/java/org/layer/domain/auth/service/AuthService.java
- layer-api/src/main/java/org/layer/domain/jwt/exception/AuthExceptionType.java
- layer-api/src/main/java/org/layer/domain/member/service/MemberService.java
- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- layer-api/src/test/java/org/layer/domain/auth/service/AuthServiceTest.java
- layer-api/src/test/java/org/layer/domain/member/service/MemberServiceTest.java
- layer-domain/src/main/java/org/layer/domain/member/entity/Member.java
- layer-domain/src/main/java/org/layer/domain/member/repository/MemberCustomRepository.java
- layer-domain/src/main/java/org/layer/domain/member/repository/MemberRepository.java
- layer-domain/src/main/java/org/layer/domain/member/repository/MemberRepositoryImpl.java
- layer-external/src/main/java/org/layer/global/exception/AuthExceptionType.java
**1. [엔티티, DB 수정] Member 엔티티에서 socialType, socialId 복합 유니크 제약 삭제**
탈퇴 후 같은 회원이 같은 소셜로그인 방식으로 재가입 가능하도록 해당 제약 조건을 삭제했습니다.
dev, prod DB에는 아직 적용돼있지 않으며 배포 시점에 반영하겠습니다.
**2. MemberRepository 구조 리팩토링과 멤버를 조회하는 메서드 수정**
- 잘못 구현 되어 있던 멤버 조회 메서드를 수정하였습니다. (소프트 딜리트이기에 deletedAt이 null인 것만 조회되어야 하는데, 해당 조건이 누락되어 있었음)
- 리포지토리 구조를 MemberRepository, MemberCustomRepository, MemberRepositoryImpl 구조로 리팩토링했습니다. 더 좋은 구조가 있다면 추천해주셔도 좋습니다!
현재 구조:
**3. 회원가입, 탈퇴를 테스트하는 MemberService, AuthService 테스트 코드 추가** 
- MemberServiceTest: 탈퇴 후 조회되지 않음을 테스트(soft delete가 제대로 되는지)
- MemberServiceTest: 탈퇴 후 재가입 테스트
- AuthServiceTest: 동시 회원가입 호출 시 1번만 처리됨을 테스트
- feat/
- closed #336
> fix: 중복 회원가입, 탈퇴 버그 수정

- layer-admin/src/main/java/org/layer/admin/space/service/AdminSpaceService.java
- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- layer-api/src/test/java/org/layer/domain/answer/service/AnswerServiceTest.java
- layer-api/src/test/java/org/layer/domain/retrospect/service/RetrospectServiceTest.java
- layer-api/src/test/resources/sql/answer-service-test-data.sql
- layer-batch/src/main/java/org/layer/batch/retrospect/RetrospectScheduler.java
- layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
- layer-event/src/main/java/org/layer/event/space/CreateSpaceEvent.java
- 회고가 마감된 시점에서는 마감기한이 null 일 수 없다.
- space 생성 이벤트가 발생했을 때, spaceId도 함께 필드값에 주입한다.
- feat/
- closed #4141
> fix: spaceId 주입 오류 및 마감기한 설정 오류 해결

- layer-admin/src/main/java/org/layer/admin/retrospect/entity/AdminRetrospectImpressionClick.java
- layer-admin/src/main/java/org/layer/admin/retrospect/enums/AdminRetrospectStatus.java
- layer-admin/src/main/java/org/layer/admin/retrospect/listener/RetrospectClickEventListener.java
- layer-admin/src/main/java/org/layer/admin/retrospect/repository/AdminRetrospectImpressionClickRepository.java
- layer-admin/src/main/java/org/layer/admin/retrospect/service/AdminRetrospectService.java
- layer-admin/src/main/java/org/layer/admin/space/entity/AdminSpaceImpressionClick.java
- layer-admin/src/main/java/org/layer/admin/space/listener/SpaceClickEventListener.java
- layer-admin/src/main/java/org/layer/admin/space/repository/AdminSpaceImpressionClickRepository.java
- layer-admin/src/main/java/org/layer/admin/space/service/AdminSpaceService.java
- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- layer-api/src/main/java/org/layer/domain/question/service/QuestionService.java
- layer-api/src/main/java/org/layer/domain/stats/StatsRetrospectApi.java
- layer-api/src/main/java/org/layer/domain/stats/StatsRetrospectController.java
- layer-api/src/main/java/org/layer/domain/stats/StatsRetrospectService.java
- layer-api/src/main/java/org/layer/domain/stats/StatsSpaceApi.java
- layer-api/src/main/java/org/layer/domain/stats/StatsSpaceController.java
- layer-api/src/main/java/org/layer/domain/stats/StatsTemplateApi.java
- layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
- layer-domain/src/test/java/org/layer/domain/retrospect/entity/RetrospectTest.java
- layer-event/src/main/java/org/layer/event/retrospect/ClickRetrospectEvent.java
- layer-event/src/main/java/org/layer/event/space/ClickSpaceEvent.java
- 회고 스페이스와 회고에 대한 CTR 관련 저장 로직을 구현했습니다.
- feat/
- closed #430
> [admin] feat: 회고 관련 CTR 저장 로직 구현
