- README.md
- PR 테스트 겸 올려봤습니다!
- 리드미 전체 파일을 PR로 올리려고 했는데 실수로 main에 바로 푸시해버렸네요.. 죄송합니다..
- 러프하게 readme나 템플릿을 작성했기 때문에 회의시간에 한 번 논의하면서 수정사항들 바로 반영하도록 하겠습니다!
- feat/#3 -> main
- closed #3
> [feat/#3] PR 테스트

- .gitignore
- build.gradle
- layer-api/src/main/java/org/layer/api/controller/HelloController.java
- layer-api/src/main/java/org/layer/auth/api/AuthController.java
- layer-api/src/main/java/org/layer/auth/jwt/JwtAuthenticationFilter.java
- layer-api/src/main/java/org/layer/auth/jwt/MemberAuthentication.java
- layer-api/src/main/java/org/layer/auth/service/JwtService.java
- layer-api/src/main/java/org/layer/config/RedisConfig.java
- 컴파일 오류 발생한 것을 수정했습니다!
- 추가로 yml 작업도 새로 이슈만들어서 하겠습니다!
- fix/#12
> fix: 컴파일 에러 수정

- layer-domain/src/main/java/org/layer/domain/member/entity/Member.java
- `Member.java`에서 enum 타입 필드 위에 `@Enumerated(value = EnumType.STRING)`를 추가
붙이면 DB에 이렇게 저장됩니다
- fix/#LS-14 -> develop
- closed #
> fix/LS-14 Member 엔티티 수정

- build.gradle
> chore: auth

- .gitignore
- build.gradle
- layer-api/src/main/java/org/layer/config/RedisConfig.java
- layer-api/src/main/java/org/layer/config/SecurityConfig.java
- layer-api/src/main/java/org/layer/domain/auth/controller/AuthApi.java
- layer-api/src/main/java/org/layer/domain/auth/controller/AuthController.java
- layer-api/src/main/java/org/layer/domain/auth/controller/dto/ReissueTokenRequest.java
- layer-api/src/main/java/org/layer/domain/auth/controller/dto/SignOutRequest.java
- layer-api/src/main/java/org/layer/domain/auth/controller/dto/WithdrawMemberRequest.java
- layer-api/src/main/java/org/layer/domain/auth/service/AuthService.java
- layer-api/src/main/java/org/layer/domain/jwt/JwtAuthenticationFilter.java
- layer-api/src/main/java/org/layer/domain/jwt/JwtValidator.java
- layer-api/src/main/java/org/layer/domain/jwt/service/JwtService.java
- layer-api/src/main/java/org/layer/domain/member/service/MemberService.java
- layer-api/src/main/java/org/layer/domain/member/service/MemberUtil.java
- layer-common/src/main/java/org/layer/common/exception/MemberExceptionType.java
- layer-domain/src/main/java/org/layer/domain/member/repository/MemberRepository.java
- layer-external/build.gradle
- layer-external/src/main/java/org/layer/oauth/dto/service/google/GoogleGetMemberInfoServiceResponse.java
- layer-external/src/main/java/org/layer/oauth/service/GoogleService.java
- layer-external/src/main/java/org/layer/oauth/service/KakaoService.java
- layer-external/src/main/java/org/layer/oauth/service/OAuthService.java
**문서화**
- `AuthApi` 인터페이스를 만들고 Swagger 문서화 작업을 했습니다.
**리팩토링, 수정 및 리뷰 반영**
- LS-6 리뷰 사항을 (시간상 일부만,,) 반영했습니다.
- 기존 토큰 재발급 로직에서 잘못된 점을 발견하여 수정했습니다.
**기능 구현**
-`hard delete` 방식으로 회원 탈퇴 기능을 구현했습니다.
- 한분이 리뷰 주시는대로 바로 머지하겠습니다..!
- refactor/#LS-17
- closed #22
> refactor/LS-17: 인증 관련 코드 리뷰 반영, 리팩토링, 탈퇴 구현, Swagger 작업

- .gitignore
- layer-api/src/main/java/org/layer/domain/actionItem/api/ActionItemApi.java
- layer-api/src/main/java/org/layer/domain/actionItem/controller/ActionItemController.java
- layer-api/src/main/java/org/layer/domain/actionItem/dto/CreateActionItemRequest.java
- layer-api/src/main/java/org/layer/domain/actionItem/dto/CreateActionItemResponse.java
- layer-api/src/main/java/org/layer/domain/actionItem/dto/DeleteActionItemRequest.java
- layer-api/src/main/java/org/layer/domain/actionItem/dto/MemberActionItemResponse.java
- layer-api/src/main/java/org/layer/domain/actionItem/dto/TeamActionItemRequest.java
- layer-api/src/main/java/org/layer/domain/actionItem/service/ActionItemService.java
- layer-domain/src/main/java/org/layer/domain/actionItem/entity/ActionItem.java
- layer-domain/src/main/java/org/layer/domain/actionItem/enums/ActionItemStatus.java
- layer-domain/src/main/java/org/layer/domain/actionItem/repository/ActionItemRepository.java
- 액션 아이템 생성 API를 작성했습니다
- feat/LS-27
- closed #
> feat/LS-27: 액션 아이템 생성 API

- layer-api/src/main/java/org/layer/config/AuthValueConfig.java
> chore/LS-36: 액세스 토큰 expiration 수정

- .github/workflows/ci-cd-compose.yaml
chore: ssh-action 최신버전 이슈로 인해 구버전으로 변경했어요.
- feat/
- closed #
> chore: 깃허브 액션 플러그인 변경

- layer-api/src/main/java/org/layer/LayerApplication.java
- layer-domain/src/main/java/org/layer/domain/common/time/RealTime.java
- 컴포넌트 스캔 관련해서 오류가 있었습니다.
- RealTime 클래스에 컴포넌트를 추가해서 해결했습니다.
- feat/
- closed #
> fix/LS-35: 컴포넌트 스캔 오류 해결

- layer-api/src/main/java/org/layer/domain/space/dto/SpaceRequest.java
- layer-api/src/main/java/org/layer/domain/space/dto/SpaceResponse.java
- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- layer-common/src/main/java/org/layer/common/exception/GlobalExceptionHandler.java
- layer-domain/src/main/java/org/layer/domain/form/entity/Form.java
- layer-domain/src/main/java/org/layer/domain/space/converter/SpaceFieldConverter.java
- layer-domain/src/main/java/org/layer/domain/space/dto/SpaceWithMemberCount.java
- layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
- layer-domain/src/main/java/org/layer/domain/space/entity/SpaceField.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceCustomRepository.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
> feat: 스페이스 생성 시 필드 복수개로 변경

- layer-api/src/main/java/org/layer/domain/external/dto/ExternalResponse.java
- layer-api/src/main/java/org/layer/domain/space/dto/SpaceResponse.java
- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- layer-common/src/main/java/org/layer/common/exception/ExternalExceptionType.java
- layer-domain/src/main/java/org/layer/domain/space/dto/SpaceWithMemberCount.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
- layer-external/src/main/java/org/layer/external/ncp/exception/ExternalException.java
- layer-external/src/main/java/org/layer/external/ncp/service/NcpService.java
스페이스 조회 API에 배너 응답이 추가됩니다
- feat/
- closed #55
> feat: 스페이스 조회 API 배너 추가

- .github/workflows/ci-cd-compose.yaml
> fix: checkout 액션 명령어 오류 수정

- layer-api/src/main/java/org/layer/domain/jwt/JwtAuthenticationFilter.java
- layer-api/src/main/java/org/layer/domain/space/api/SpaceApi.java
- layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
- layer-api/src/main/java/org/layer/domain/space/dto/SpaceResponse.java
- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
스페이스 생성하기 API에서 생성된 스페이스의 아이디를 반환합니다
- feat/
- closed #58
> feat: 생성된 스페이스 아이디 반환하기

- layer-api/src/main/java/org/layer/domain/space/controller/SpaceApi.java
- layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
- layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceRequest.java
스페이스 떠나기 POST요청의 Body를 활용하도록 변경했습니다
- feat/
- closed #
> fix: 스페이스 떠나기 요청방식변경

- layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectApi.java
- layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectController.java
- layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/response/RetrospectCreateResponse.java
- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- layer-api/src/main/java/org/layer/domain/space/controller/SpaceApi.java
- layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
- layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceRequest.java
- layer-api/src/main/java/org/layer/domain/template/controller/dto/AllTemplatesRequest.java
> Feat/#69 fix 스페이스 떠나기 요청방식변경

- layer-api/src/main/resources/application-dev.yml
> fix: 환경변수 경로 오류 수정

- layer-api/src/main/resources/console-appender.xml
날짜기반의 로그명을 사용하려했으나, 수집기에 날짜가 기록됨으로,
하나의 파일로 통일했습니다
- feat/
- closed #
> chore: 로그파일명 변경

- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
> fix: 회고 작성 @Transactional 추가

- layer-api/src/main/java/org/layer/domain/template/service/TemplateService.java
- layer-api/src/main/resources/application-dev.yml
- layer-domain/src/main/java/org/layer/domain/form/repository/FormRepository.java
List 반환값 dto로 감싸기  -> 이거 제외 리뷰 사항 반영했습니다!
- 템플릿 전체 조회 아이디로 가져옴 -> `FormType.TEMPLATE` 으로 가져오는 것으로 변경
- 필요없는 log 코드 삭제
- fix/83
- close #83
> fix/83: 템플릿 조회 리뷰 사항 반영

- layer-api/src/main/resources/console-appender.xml
Rolling Policy를 변경하여 하나의 파일에 로그가 수집되로록 변경했습니다.
- feat/
- closed #
> fix: 로그백 경로 수정

- layer-api/src/main/java/org/layer/aop/ExecutionLoggingAop.java
- Ruquest URI 를 추가했습니다!
- feat/#88 -> dev
- closed #88
> refactor: 로깅 URI 추가

- layer-api/src/main/java/org/layer/domain/template/controller/dto/TemplateDetailInfoResponse.java
- layer-api/src/main/java/org/layer/domain/template/controller/dto/TemplateSimpleInfoResponse.java
- layer-api/src/main/resources/application-dev.yml
- layer-domain/src/main/java/org/layer/domain/form/entity/Form.java
- layer-domain/src/main/java/org/layer/domain/form/enums/FormTag.java
- layer-domain/src/main/java/org/layer/domain/template/entity/TemplateMetadata.java
- `FormTag` enum을 추가했습니다.
- `Form` 엔티티에 formTag를 추가했습니다.
- `TemplateMetadata` 테이블에서 `templateName`, `firstTag`,`secondTag`를 삭제했습니다.
- chore/92
- closed #92
> chore/92: FormTag enum 추가, Form, TemplateMetadata 엔티티 수정

- layer-api/src/main/java/org/layer/domain/jwt/JwtAuthenticationFilter.java
- layer-api/src/main/java/org/layer/domain/space/controller/SpaceApi.java
- layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
- layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceRequest.java
- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- layer-common/src/main/java/org/layer/common/exception/SpaceExceptionType.java
- layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepository.java
- 스페이스 대표자 변경하기
- 스페이스 대표자가 특정 멤버 추방하기
- 스페이스 대표자 변경하기
- 스페이스 멤버 추방하기
- feat/
- closed #91
> feat: 대표자 변경 API & 팀원 삭제 API

- .github/workflows/ci-cd-compose.yaml
인스턴스 용량 과부하 방지용 이미지 정리 스탭을 추가했습니다.
- feat/
- closed #
> chore: 미사용 이미지 정리 스탭 추가

- layer-api/src/main/java/org/layer/domain/answer/controller/dto/request/AnswerCreateRequest.java
- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- FE 요청에 따라 변경했습니다.
- feat/
- closed #
> chore: answerContent 로 변경

- layer-api/src/main/java/org/layer/domain/space/controller/SpaceApi.java
- layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
- layer-domain/src/main/java/org/layer/domain/space/repository/MemberSpaceRelationRepository.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepository.java
- 스페이스 삭제하기 기능을 추가했어요.
- 스페이스 삭제 시 소속된 멤버정보도 함께 삭제되요
```
Hibernate: 
select
s1_0.id,
s1_0.banner_url,
s1_0.category,
s1_0.form_id,
s1_0.leader_id,
s1_0.name,
s1_0.updated_at 
from
space s1_0 
where
s1_0.id=?
Hibernate: 
delete 
from
where
msr1_0.space_id=?
Hibernate: 
select
s1_0.id,
s1_0.banner_url,
s1_0.category,
s1_0.form_id,
s1_0.leader_id,
s1_0.name,
s1_0.updated_at 
from
space s1_0 
where
s1_0.id=?
Hibernate: 
delete 
from
space 
where
id=?
```
- feat/
- closed #99
> feat: 스페이스 삭제하기 API

- layer-api/src/main/java/org/layer/domain/answer/controller/AnswerApi.java
- layer-api/src/main/java/org/layer/domain/answer/controller/AnswerController.java
- layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/AnswerByPersonGetResponse.java
- layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/AnswerByQuestionGetResponse.java
- layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/AnswerListGetResponse.java
- layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/PersonAndAnswerGetResponse.java
- layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/QuestionAndAnswerGetResponse.java
- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- layer-common/src/main/java/org/layer/common/exception/RetrospectExceptionType.java
- layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
- layer-domain/src/main/java/org/layer/domain/answer/repository/AnswerRepository.java
- layer-domain/src/main/java/org/layer/domain/member/entity/Members.java
- layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
- 회고 분석 조회 로직을 구현했습니다.
* 조회결과 첨부하겠습니다! FE에서 질문별, 사람별 분석 데이터를 요청해서 이렇게 만들었습니다..!
```
{
"questions": [
{
"questionContent": "회고 질문1",
"questionType": "number",
"answers": [
{
"name": "송민규",
"answerContent": "답변1-1"
},
{
"name": "1송민규",
"answerContent": "답변2-1"
},
{
"name": "2송민규",
"answerContent": "답변3-1"
}
]
},
{
"questionContent": "회고 질문2",
"questionType": "plain_text",
"answers": [
{
"name": "송민규",
"answerContent": "답변1-2"
},
{
"name": "1송민규",
"answerContent": "답변2-2"
},
{
"name": "2송민규",
"answerContent": "답변3-2"
}
]
},
{
"questionContent": "회고 질문3",
"questionType": "plain_text",
"answers": [
{
"name": "송민규",
"answerContent": "답변1-3"
},
{
"name": "1송민규",
"answerContent": "답변2-3"
},
{
"name": "2송민규",
"answerContent": "답변3-3"
}
]
}
],
"individuals": [
{
"name": "송민규",
"answers": [
{ …
```
> feat: 회고 분석 조회 API 

- layer-api/src/main/java/org/layer/domain/actionItem/service/ActionItemService.java
> fix: create actionitem 수정

- layer-api/src/main/java/org/layer/domain/answer/controller/AnswerApi.java
- layer-api/src/main/java/org/layer/domain/answer/controller/AnswerController.java
- layer-api/src/main/java/org/layer/domain/answer/controller/dto/request/AnswerListUpdateRequest.java
- layer-api/src/main/java/org/layer/domain/answer/controller/dto/request/AnswerUpdateRequest.java
- layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/WrittenAnswerGetResponse.java
- layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/WrittenAnswerListResponse.java
- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- layer-common/src/main/java/org/layer/common/exception/AnswerExceptionType.java
- layer-domain/src/main/java/org/layer/domain/answer/entity/Answer.java
- layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
- layer-domain/src/main/java/org/layer/domain/answer/repository/AnswerRepository.java
- layer-domain/src/main/java/org/layer/domain/question/repository/QuestionRepository.java
- 마감되지 않은 회고에 대해 다음 2가지 기능을 추가했어요.
- 완료된 내 답변 조회하기
- 완료된 내 답변 수정하기
- Feat/#114 
- closed #114
> feat: 내가 작성한 회고 수정하기

- build.gradle
- layer-api/src/main/resources/application-test.yml
- layer-api/src/test/java/org/layer/LayerApplicationTests.java
- layer-api/src/test/java/org/layer/domain/retrospect/service/RetrospectServiceTest.java
- layer-domain/src/test/java/layer/domain/TestConfiguration.java
- layer-domain/src/test/java/layer/domain/retrospect/entity/RetrospectTest.java
- layer-domain/src/test/java/layer/domain/retrospect/repository/RetrospectRepositoryTest.java
- 테스트 코드 환경을 만들었습니다.
- feat/#120 -> dev
- closed #120
> test: 테스트코드 환경 세팅

- layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/AnswerByPersonGetResponse.java
- layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/AnswerByQuestionGetResponse.java
- layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/AnswerListGetResponse.java
- layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/PersonAndAnswerGetResponse.java
- layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/QuestionAndAnswerGetResponse.java
- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- layer-domain/src/main/java/org/layer/domain/form/enums/FormTag.java
- FE 요청에 따라 enum 변경했습니다.
- 스웨거 누락된 내용 채웠습니다.
- feat/#122 -> dev
- closed #122
> chore: enum 변경 및 스웨거 추가

- layer-domain/src/main/java/org/layer/domain/analyze/entity/Analyze.java
> bug: 테이블 이름 변경

- layer-api/src/main/java/org/layer/domain/actionItem/service/ActionItemService.java
- layer-domain/src/main/java/org/layer/domain/actionItem/dto/MemberActionItemResponse.java
- layer-domain/src/main/java/org/layer/domain/answer/entity/Answer.java
- 실행 중 / 완료 상태 값, 답변 작성 시간을 추가했습니다.
- feat/
- closed #160
> chore: 멤버 실행 목표 응답값 수정

- layer-api/src/main/java/org/layer/domain/form/controller/dto/request/RecommendFormQueryDto.java
- layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
- 작은 오류들이 있어서 수정했습니다.
- feat/
- closed #159
> chore: 추천 템플릿 조회 API 및 회고 수정 API 변경

- layer-api/src/main/java/org/layer/domain/actionItem/controller/ActionItemApi.java
- layer-api/src/main/java/org/layer/domain/actionItem/controller/ActionItemController.java
- layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/request/ActionItemCreateBySpaceIdRequest.java
- layer-api/src/main/java/org/layer/domain/actionItem/service/ActionItemService.java
- layer-common/src/main/java/org/layer/common/exception/ActionItemExceptionType.java
> feat: 스페이스 아이디로 진행 중 회고에 실행 목표 추가

- layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/response/RetrospectActionItemResponse.java
- layer-api/src/main/java/org/layer/domain/actionItem/service/ActionItemService.java
- layer-domain/src/main/java/org/layer/domain/actionItem/dto/MemberActionItemResponse.java
> Chore/170: 실행목표 조회 API 응답 수정

- layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceResponse.java
- layer-domain/src/main/java/org/layer/domain/space/dto/SpaceWithMemberCount.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
- 스페이스 단건 조회에 formTag 추가했습니다.
- 맥락 : https://depromeet-15th.slack.com/archives/C075SR4HZUG/p1724080818924849
- querydsl 의 sql이 변화되었는데 제가 의도에 맞게 수정한건지 한번만 확인 부탁드립니다!! @raymondanythings 
- feat/
- closed #172
> chore: 스페이스 단건 조회 formTag 추가

- layer-api/src/main/java/org/layer/domain/actionItem/controller/ActionItemApi.java
- layer-api/src/main/java/org/layer/domain/actionItem/controller/ActionItemController.java
- layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/response/ActionItemCreateResponse.java
- layer-api/src/main/java/org/layer/domain/actionItem/service/ActionItemService.java
> chore: 실행 목표 생성 응답 수정

- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
- 질문에 대한 답변 추출 로직 오류가 있어 수정했습니다.
- feat/
- closed #179
> fix: 질문에 대한 답변 추출 로직 수정

- layer-api/src/test/java/org/layer/domain/retrospect/service/RetrospectServiceTest.java
> chore: test 코드 임시 주석 처리

- layer-api/src/main/resources/application-test.yml
- layer-api/src/test/java/org/layer/domain/retrospect/service/RetrospectServiceTest.java
> chore: 테스트 코드 임시 주석처리, yml 변경 반영

- .github/workflows/k3s.yaml
- build.gradle
- layer-batch/src/main/java/org/layer/BatchApplication.java
- layer-batch/src/main/java/org/layer/batch/scheduler/RetrospectScheduler.java
- layer-batch/src/main/resources/application.yml
- layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectCustomRepository.java
- layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectCustomRepositoryImpl.java
- layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectRepository.java
- settings.gradle
- 회고 마감 배치 작업 진행했습니다.
- db에 정상적으로 변경됐는지 확인 완료했습니다!
- 배포 스크립트 한 번만 확인해주시면 감사하겠습니다 !!
```
update
retrospect r1_0 
set
retrospect_status=? 
where
?>r1_0.deadline
```
- feat/
- closed #62
> feat: 회고 마감 배치 작업 및 배포스크립트 수정

- layer-api/src/main/java/org/layer/LayerApplication.java
- layer-api/src/main/java/org/layer/domain/analyze/controller/AnalyzeApi.java
- layer-api/src/main/java/org/layer/domain/analyze/controller/AnalyzeController.java
- layer-api/src/main/java/org/layer/domain/analyze/controller/dto/response/AnalyzeDetailResponse.java
- layer-api/src/main/java/org/layer/domain/analyze/controller/dto/response/AnalyzeGetResponse.java
- layer-api/src/main/java/org/layer/domain/analyze/controller/dto/response/AnalyzesGetResponse.java
- layer-api/src/main/java/org/layer/domain/analyze/service/AnalyzeService.java
- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- layer-domain/src/main/java/org/layer/domain/analyze/entity/Analyze.java
- layer-domain/src/main/java/org/layer/domain/analyze/entity/AnalyzeDetail.java
- layer-domain/src/main/java/org/layer/domain/analyze/enums/AnalyzeDetailType.java
- layer-domain/src/main/java/org/layer/domain/analyze/enums/AnalyzeType.java
- layer-domain/src/main/java/org/layer/domain/analyze/repository/AnalyzeRepository.java
- layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
- layer-domain/src/main/java/org/layer/domain/answer/repository/AnswerRepository.java
- layer-domain/src/main/java/org/layer/domain/space/entity/Team.java
- layer-external/src/main/java/org/layer/external/ai/constant/OpenAIFactory.java
- layer-external/src/main/java/org/layer/external/ai/dto/request/Properties.java
- layer-external/src/main/java/org/layer/external/ai/dto/response/OpenAIResponse.java
- 회고분석에 대해 전면 수정했습니다.
- 맥락 : https://depromeet-15th.slack.com/archives/C075SR4HZUG/p1724721648163649
- 회고 마감이 될 때, 비동기적(`Async`)으로 회고 분석을 생성하도록 구현했습니다.
- 팀별 분석뿐만 아니라 개인 분석도 추가했습니다.
- `layer-batch` 에서도 ai 분석을 호출해야하는데 아직 인프라가 안정적이지 않은거 같아서 그 부분부터 먼저보려고 했습니다.
```
{
"teamAnalyze": {
"scoreOne": 0,
"scoreTwo": 1,
"scoreThree": 0,
"scoreFour": 1,
"scoreFive": 0,
"goalCompletionRate": 2,
"goodPoints": [
{
"content": "팀 간 협업의 원활함",
"count": 3,
"analyzeDetailType": "GOOD"
},
{
"content": "팀원 피드백을 통한 개인 성장",
"count": 2,
"analyzeDetailType": "GOOD"
},
{
"content": "성과 초과 달성에 대한 만족감",
"count": 2,
"analyzeDetailType": "GOOD"
}
],
"badPoints": [
{
"content": "예산 초과 문제",
"count": 2,
"analyzeDetailType": "BAD"
},
{
"content": "기술적 문제로 인한 일정 지연",
"count": 1,
"analyzeDetailType": "BAD"
},
{
"content": …
```
> feat: 회고 분석 기능 전면 수정

- layer-api/src/main/java/org/layer/domain/analyze/controller/dto/response/AnalyzeIndividualGetResponse.java
- layer-api/src/main/java/org/layer/domain/analyze/controller/dto/response/AnalyzeTeamGetResponse.java
- layer-api/src/main/java/org/layer/domain/analyze/controller/dto/response/AnalyzesGetResponse.java
- layer-api/src/main/java/org/layer/domain/analyze/service/AnalyzeService.java
- 개인 분석 응답값을 수정했습니다.
- `individualAnalyze` 부분이 컴팩트하게 문장만 나오도록 수정되었습니다.
```
{
"teamAnalyze": {
"scoreOne": 0,
"scoreTwo": 1,
"scoreThree": 0,
"scoreFour": 1,
"scoreFive": 0,
"goalCompletionRate": 2,
"goodPoints": [
{
"content": "팀 간 협업 개선",
"count": 3,
"analyzeDetailType": "GOOD"
},
{
"content": "성과 달성의 기쁨",
"count": 2,
"analyzeDetailType": "GOOD"
},
{
"content": "기술 스택 개선",
"count": 2,
"analyzeDetailType": "GOOD"
}
],
"badPoints": [
{
"content": "예산 초과 문제",
"count": 2,
"analyzeDetailType": "BAD"
},
{
"content": "테스트 환경 불안정",
"count": 1,
"analyzeDetailType": "BAD"
},
{
"content": "요구 사항 정의 부족",
"count": 1,
"analyzeDetailType": "BAD"
}
],
"improvementPoints": [
{
"content": "예산 관리 절차 개선",
"count": 2,
"analyzeDetailType": "IMPROVEMENT"
},
{
"content": "테스트 환경 안정화",
"count": 1, …
```
> chore: 개인 ai 분석 응답값 수정

- build.gradle
- layer-api/src/main/java/org/layer/domain/analyze/controller/AnalyzeController.java
- layer-api/src/main/java/org/layer/domain/analyze/service/AnalyzeService.java
- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- layer-batch/src/main/java/org/layer/batch/scheduler/RetrospectScheduler.java
- layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
- layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectRepository.java
- layer-external/src/main/java/org/layer/external/ai/service/AIAnalyzeService.java
- 개인 스페이스 내 회고 일 경우, 팀 관련 회고 Null 값 되도록 했습니다.
- batch 모듈에서 AI 응답을 생성하게끔 만들었습니다.
- feat/
- closed #193
> chore: 분석 로직 수정

- layer-api/src/main/java/org/layer/config/SecurityConfig.java
- layer-api/src/main/java/org/layer/domain/auth/controller/AuthController.java
> chore: 임시 api 생성

- layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/RetrospectCreateRequest.java
- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- formTag 생성 방식을 변경했습니다.
- feat/
- closed #197
> chore: formTag 생성 방식 변경

- layer-api/src/main/java/org/layer/domain/member/controller/MemberApi.java
- layer-api/src/main/java/org/layer/domain/member/controller/MemberController.java
- layer-api/src/main/java/org/layer/domain/member/controller/dto/GetMemberAnalyzesResponse.java
- layer-api/src/main/java/org/layer/domain/member/controller/dto/GetMemberRecentAnalyzeResponse.java
- layer-api/src/main/java/org/layer/domain/member/controller/dto/GetMemberRecentBadAnalyzeResponse.java
- layer-api/src/main/java/org/layer/domain/member/controller/dto/GetMemberRecentGoodAnalyzeResponse.java
- layer-api/src/main/java/org/layer/domain/member/controller/dto/GetMemberRecentImprovementAnalyzeResponse.java
- layer-api/src/main/java/org/layer/domain/member/service/MemberService.java
- layer-domain/src/main/java/org/layer/domain/analyze/entity/Analyze.java
- layer-domain/src/main/java/org/layer/domain/analyze/repository/AnalyzeRepository.java
- layer-domain/src/main/java/org/layer/domain/retrospect/dto/SpaceRetrospectDto.java
- layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectRepository.java
- layer-domain/src/main/java/org/layer/domain/space/repository/MemberSpaceRelationRepository.java
- 쿼리가 너무 복잡해서 N+1 조회 하게 되었습니다. 이 부분은 꼭 개선했음 좋겠습니다. 더 좋은 의견 있으시면 말씀주세요!
```
{
"recentAnalyzes": [
{
"spaceId": 424,
"spaceName": "레이어",
"retrospectId": 213,
"retrospectTitle": "중간 발표 회고",
"deadline": "2024-08-19T12:00:00"
},
{
"spaceId": 479,
"spaceName": "면접준비",
"retrospectId": 262,
"retrospectTitle": "오늘 면접 회고록",
"deadline": "2024-08-28T03:00:00"
},
{
"spaceId": 463,
"spaceName": "떡잎마을방법대",
"retrospectId": 252,
"retrospectTitle": "8월 회고",
"deadline": "2024-08-31T00:00:00"
}
],
"goodAnalyzes": [
{
"spaceId": 424,
"spaceName": "레이어",
"retrospectId": 213,
"retrospectTitle": "중간 발표 회고",
"deadline": "2024-08-19T12:00:00",
"goodPoint": "Effective teamwork"
},
{
"spaceId": 479,
"spaceName": "면접준비",
"retrospectId": 262,
"retrospectTitle": "오늘 면접 회고록",
"deadline": "2024-08-28T03:00:00", …
```
> feat: 내 분석 조회 API 구현

- layer-api/src/main/java/org/layer/domain/form/controller/FormController.java
- layer-api/src/main/java/org/layer/domain/form/service/FormService.java
- layer-domain/src/main/java/org/layer/domain/form/enums/FormTag.java
- layer-domain/src/main/java/org/layer/domain/form/enums/RetrospectPurpose.java
- layer-domain/src/main/java/org/layer/domain/form/repository/FormRepository.java
- 기존에 로직에서 추천 로직을 수정했습니다.
- 각각의 항목마다 누적합을 해서 최댓값을 반환하도록 구현했습니다.
```
Hibernate: 
select
f1_0.id,
f1_0.created_at,
f1_0.form_tag,
f1_0.form_type,
f1_0.introduction,
f1_0.member_id,
f1_0.space_id,
f1_0.title,
f1_0.updated_at 
from
form f1_0 
where
f1_0.form_tag=? 
and f1_0.form_type=?
Hibernate: 
select
tm1_0.id,
tm1_0.created_at,
tm1_0.form_id,
tm1_0.template_image_url,
tm1_0.tip_description,
tm1_0.tip_title,
tm1_0.updated_at 
from
template_metadata tm1_0 
where
tm1_0.form_id=?
```
- fix/#210 -> dev
- closed #210
> fix: 템플릿 추천 로직 수정

- layer-api/src/main/java/org/layer/domain/form/service/FormService.java
- layer-domain/src/main/java/org/layer/domain/common/random/CustomRandom.java
- layer-domain/src/main/java/org/layer/domain/common/random/MockRandom.java
- layer-domain/src/main/java/org/layer/domain/common/random/RealRandom.java
- layer-domain/src/main/java/org/layer/domain/form/enums/FormTag.java
- 추천 템플릿이 중복인 경우, 그 중에서 랜덤으로 하나 선택하도록 수정했습니다.
- feat/
- closed #219
> chore: 추천 템플릿이 중복인 경우, 그 중에서 랜덤으로 하나 선택하도록 수정

- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
> hotfix: 회고 생성 오류 해결

- layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
> hotfix: NPE 해결

- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- Async 메서드와 엔티티를 저장하는 코드 간의 싱크가 맞지 않아 오류가 발생했습니다. 
- 이를 해결하기 위해 flush를 진행 -> AI 서비스 로직이 돌아가도록 수정했습니다.
- feat/
- closed #230
> fix: AI 서비스와 싱크 맞지 않는 오류 해결

- layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
- 분석상태가 DONE 으로 되지 않는 오류 해결
- feat/
- closed #233
> fix: 분석상태가 DONE 으로 되지 않는 오류 해결

- layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
> hotfix: 분석상태가 DONE 으로 되지 않는 오류 해결 (#234)

- layer-api/src/main/java/org/layer/domain/actionItem/service/ActionItemService.java
-  만료기간이 없는 회고의 경우 nullable 객체 정렬 코드 변경
- feat/
- closed #
> fix: nullable 객체 정렬 코드 변경

- layer-external/src/main/java/org/layer/external/ai/service/AIAnalyzeService.java
- 회고 마감시, 더티체킹이 안되는 것을 확인했습니다. @Async 이슈같긴 한데 일단 save 메서드 추가해서 PR 올렸습니다.
- feat/
- closed #239
> fix: 회고 마감 로직 수정

- layer-api/src/main/resources/application-prod.yml
프로덕션용 환경변수를 추가했어요.
- feat/
- closed #
> chore: 환경변수 변경

- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- 이미 마감되었을 경우 분석 로직 실행시키지 않도록 수정했습니다.
- feat/
- closed #242
> fix: 이미 마감되었을 경우 분석 로직 실행시키지 않도록 수정

- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
> fix: 임시답변 제외하고 조회하도록 수정

- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
> hotfix: 임시답변 제외하고 조회하도록 수정

- layer-api/src/main/resources/application-dev.yml
- layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
- layer-domain/src/test/java/layer/domain/retrospect/entity/RetrospectTest.java
- layer-domain/src/test/java/layer/domain/retrospect/repository/RetrospectRepositoryTest.java
- 회고 수정 기능 버그 수정했습니다.
- feat/
- closed #249
> fix: 회고 수정 기능 버그

- layer-batch/src/main/resources/application.yml
- db 방향 변경
- feat/
- closed #251
> fix: 배치 서버 db 방향 변경

- layer-domain/src/main/java/org/layer/domain/member/entity/Member.java
> fix: Table 어노테이션으로 복합 유니크 제약조건 추가 (#262)

- layer-batch/src/main/resources/application.yml
- layer-domain/src/main/java/org/layer/domain/member/entity/Member.java
> fix: layer-batch > application.yml에 디스코드 정보 추가

- .gitignore
- build.gradle
- layer-admin/src/main/java/org/layer/common/exception/AdminException.java
- layer-admin/src/main/java/org/layer/config/RedisConfigDev.java
- layer-admin/src/main/java/org/layer/config/RedisConfigProd.java
- layer-admin/src/main/java/org/layer/member/controller/dto/GetMemberActivityResponse.java
- layer-admin/src/main/java/org/layer/member/service/AdminMemberService.java
- layer-admin/src/main/resources/application-dev.yml
- layer-admin/src/main/resources/application-local.yml
- layer-admin/src/main/resources/application-prod.yml
- layer-api/src/main/java/org/layer/aop/RecentAccessHistoryAop.java
- layer-api/src/main/java/org/layer/config/RedisConfigDev.java
- layer-api/src/main/java/org/layer/config/RedisConfigProd.java
- layer-api/src/main/resources/application-dev.yml
- layer-common/src/main/java/org/layer/common/exception/AdminExceptionType.java
> chore: dev db connection 개수 조정

- .github/workflows/aws-cicd-dev.yml
- .github/workflows/aws-cicd-prod.yml
- .gitignore
- layer-api/src/test/resources/sql/answer-service-test-data.sql
- layer-api/src/test/resources/sql/delete-all-test-data.sql
> fix: gitignore 수정 및 테스트 데이터 주입

- .github/workflows/aws-cicd-dev.yml
- .github/workflows/aws-cicd-prod.yml
- layer-api/infra/development/deploy.sh
- layer-api/infra/development/docker-compose-blue.yaml
- layer-api/infra/development/docker-compose-green.yaml
- layer-api/infra/development/nginx.blue.conf
- layer-api/infra/development/nginx.green.conf
- layer-api/infra/production/deploy.sh
- layer-api/infra/production/docker-compose-blue.yaml
- layer-api/infra/production/docker-compose-green.yaml
- layer-api/infra/production/nginx.blue.conf
- layer-api/infra/production/nginx.green.conf
- layer-api/src/main/java/org/layer/domain/admin/member/controller/AdminMemberApi.java
- layer-api/src/main/java/org/layer/domain/admin/member/controller/AdminMemberController.java
- layer-api/src/main/java/org/layer/domain/admin/member/controller/dto/GetMemberActivityResponse.java
- layer-api/src/main/java/org/layer/domain/admin/member/controller/dto/GetMembersActivitiesResponse.java
- layer-api/src/main/java/org/layer/domain/admin/member/service/AdminMemberService.java
- layer-api/src/main/java/org/layer/domain/admin/retrospect/controller/AdminRetrospectApi.java
- layer-api/src/main/java/org/layer/domain/admin/retrospect/controller/AdminRetrospectController.java
- layer-api/src/main/java/org/layer/domain/admin/retrospect/controller/dto/AdminRetrospectCountGetResponse.java
- layer-api/src/main/java/org/layer/domain/admin/retrospect/controller/dto/AdminRetrospectsGetResponse.java
- layer-api/src/main/java/org/layer/domain/admin/retrospect/service/AdminRetrospectService.java
- layer-api/src/main/java/org/layer/domain/admin/space/controller/AdminSpaceApi.java
- layer-api/src/main/java/org/layer/domain/admin/space/controller/AdminSpaceController.java
- layer-api/src/main/java/org/layer/domain/admin/space/controller/dto/AdminSpaceCountGetResponse.java
- layer-api/src/main/java/org/layer/domain/admin/space/controller/dto/AdminSpacesGetResponse.java
- layer-api/src/main/java/org/layer/domain/admin/space/service/AdminSpaceService.java
- layer-api/src/main/java/org/layer/scheduler/RetrospectScheduler.java
- layer-domain/src/main/java/org/layer/domain/admin/exception/AdminException.java
소스
- layer-admin 소스를 `layer-api > src > java.org.layer > domain > admin` 패키지 하위로 이전했습니다.
- layer-admin 소스를 `layer-api > src > java.org.layer > scheduler` 패키지 하위로 이전했습니다.
aws
- 기존 2개의 t2.small 인스턴스를 삭제하고 t2.micro 2개(`layer-prod-micro`, `layer-develop-micro`)를 생성해서 컨테이너를 모두 이관했습니다.
- 스왑 메모리 적용해서 블루-그린 무중단 배포 될 수 있게 했습니다
prod 메모리
dev 메모리
제가 2/10~2/14에 연수원에 있어서 2/15 토요일에나 작업 가능할 것 같아, 천천히 리뷰해주셔도 될 것 같습니다!
이관 이후 어드민 API URI: `{{layer-api}}/admin/~~~`
6개의 api 모두 잘 동작하는 것 확인했습니다1
- feat/
- closed #
> refactor: aws t2.micro로 변경을 위해 admin, batch 소스를 layer-api로 이관

- .github/workflows/aws-cicd-dev.yml
- .github/workflows/aws-cicd-prod.yml
- layer-api/infra/development/deploy.sh
- layer-api/infra/production/deploy.sh
- layer-api/src/main/java/org/layer/LayerApplication.java
`@EnableScheduling` 추가
- feat/
- closed #
> hotfix: EnableScheduling 어노테이션 추가

- .github/workflows/aws-cicd-dev.yml
- build.gradle
- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- layer-common/src/main/java/org/layer/common/exception/RetrospectExceptionType.java
- layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
- layer-external/src/main/java/org/layer/external/ai/service/AIAnalyzeService.java
- ai 분석 관련하여 동시성 문제를 해결했습니다. 2가지 문제가 있었습니다.
1. 마지막 답변 입력 후 -> 바로 회고 마감을 클릭할 경우 분석이 2번 생기는 문제가 있었습니다.
2. 마지막 답변 입력했을 때, 회고 마감 처리가 되지 않았던 문제가 있었습니다.
- feat/
- closed #
> fix: ai 분석 동시성 문제 해결

- .github/workflows/aws-cicd-dev.yml
- .github/workflows/aws-cicd-prod.yml
- layer-api/infra/development/docker-compose-blue.yaml
- layer-api/infra/development/docker-compose-green.yaml
- layer-api/infra/production/docker-compose-blue.yaml
- layer-api/infra/production/docker-compose-green.yaml
docker-compose.yml에서 레디스의 port 부분을 제거했습니다. (외부에서 접근할 수 없도록)
- feat/
- closed #
> hotfix: redis expose port 제거

- .github/workflows/aws-cicd-dev.yml
- .github/workflows/aws-cicd-prod.yml
- layer-api/src/main/resources/application-test.yml
- 제가 예전에 수정하다가 실수가 있었던 것 같습니다. 이에 pr 단계에서 ci 실행되도록 수정했습니다.
- feat/
- closed #299
> fix: pr 단계에서 ci 실행되도록 수정

- layer-api/src/main/java/org/layer/global/exception/GlobalExceptionHandler.java
- 기존에 잘못된 url 입력시 500에러 나던 것을 400에러로 변동했습니다.
- 이로써 잘못된 입력에 대한 디스코드 알림이 더이상 나타나지 않게 되었습니다.
- feat/
- closed #302
> refactor: NoResourceFoundException 핸들링 추가

- .github/workflows/aws-cicd-dev.yml
- .github/workflows/aws-cicd-prod.yml
- layer-api/src/main/resources/application-dev.yml
- cors 에러를 해결했습니다.
- feat/
- closed #
> fix: cors 에러 해결

- layer-api/src/main/java/org/layer/config/SecurityConfig.java
- layer-api/src/main/resources/application-dev.yml
- layer-api/src/main/resources/application-local.yml
- layer-api/src/main/resources/application-prod.yml
- layer-api/src/main/resources/application-test.yml
- cors 설정을 수정하여 에러 해결
- feat/
- closed #307
> fix: cors 설정 수정

- layer-api/src/main/resources/application-dev.yml
- redis 설정 실수 해결
- feat/
- closed #
> fix: redis 설정 오류 수정

- layer-api/src/main/java/org/layer/config/SecurityConfig.java
> fix: www 관련 cors 추가

- layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceRequest.java
- 어노테이션을 실수로 사용했습니다.
- feat/
- closed #
> fix: 검증 어노테이션 오류 해결

- layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceResponse.java
- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- NPE 문제 해결했습니다.
- feat/
- closed #
> fix: NPE 문제 해결

- layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceResponse.java
- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- layer-api/src/main/java/org/layer/global/exception/ApiSpaceExceptionType.java
- layer-api/src/test/java/org/layer/domain/fixture/MemberFixture.java
- layer-api/src/test/java/org/layer/domain/space/SpaceServiceTest.java
- layer-domain/src/main/java/org/layer/domain/member/repository/MemberRepository.java
- layer-domain/src/main/java/org/layer/domain/space/entity/Team.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceCustomRepository.java
- layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
- 스페이스 팀원 목록 조회를 개선하였습니다.
- 기존 로직이 다소 보기 어려운 부분이 있어 쿼리를 분리해봤습니다.
- feat/
- closed #324
> refactor: 스페이스 팀원 목록 조회 개선

- layer-api/src/main/java/org/layer/config/AuthValueConfig.java
- layer-api/src/main/java/org/layer/domain/jwt/service/JwtService.java
- layer-api/src/main/java/org/layer/domain/member/service/MemberService.java
> fix: 리프레시 관련 임시 수정

- layer-api/src/main/java/org/layer/domain/auth/service/AuthService.java
- SignUpResponse 클래스에 of 메서드에서 member 가 null 인 문제가 있었습니다.
- 로그를 살펴보니 이미 회원가입이 되었는데 중복으로 요청할 경우, 해당 문제가 발생할 수 있음을 확인했습니다.
- 이애 이미 회원이 존재할 경우, 해당 에러를 global exception handler 에서 감지하도록 수정했습니다.
- feat/
- closed #342
> fix: 이미 회원이 존재할 경우, global exception handler 에서 감지하도록 수정

- layer-api/src/main/java/org/layer/config/SecurityConfig.java
- 어드민 프론트 도메인을 cors 설정에 추가했습니다.
- feat/
- closed #354
> chore: admin 관련 fe 도메인 추가

- layer-admin/src/main/java/org/layer/admin/auth/AdminAuthorizationInterceptor.java
- layer-admin/src/main/java/org/layer/admin/config/AdminAsyncConfig.java
- layer-admin/src/main/java/org/layer/admin/config/AdminWebConfig.java
- admin 에서 인증/인가를 위한 인터셉터를 구현했습니다.
- `/admin/**` 과 같이 `/admin`으로 시작하는 url은 해당 인터셉터를 타도록 구현했습니다.
- 추가로 admin config 관련된 것은 헷갈리지 않도록 "Admin"을 앞에 붙였습니다.
- 비밀번호는 문서화하도록 하겠습니다.
- feat/
- closed #353
> [admin] feat: 인가 인터셉터 구현

- layer-admin/src/main/java/org/layer/admin/retrospect/entity/AdminRetrospectAnswerHistory.java
- layer-admin/src/main/java/org/layer/admin/retrospect/listener/WriteRetrospectEventListener.java
- layer-admin/src/main/java/org/layer/admin/retrospect/repository/AdminRetrospectRepository.java
- layer-admin/src/main/java/org/layer/admin/retrospect/service/AdminRetrospectService.java
- layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
- layer-api/src/main/java/org/layer/domain/question/service/QuestionService.java
- layer-api/src/main/java/org/layer/global/exception/GlobalExceptionHandler.java
- layer-api/src/main/java/org/layer/scheduler/MemberActivityScheduler.java
- layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
- layer-event/src/main/java/org/layer/event/retrospect/WriteRetrospectEndEvent.java
- layer-event/src/main/java/org/layer/event/retrospect/WriteRetrospectStartEvent.java
- layer-external/src/main/java/org/layer/discord/notifier/CreateRetrospectEventNotifier.java
- layer-external/src/main/java/org/layer/discord/notifier/CreateSpaceEventNotifier.java
- layer-external/src/main/java/org/layer/discord/notifier/ErrorEvent.java
- layer-external/src/main/java/org/layer/discord/notifier/ErrorEventNotifier.java
- layer-external/src/main/java/org/layer/discord/notifier/MemberActivityEvent.java
- layer-external/src/main/java/org/layer/discord/notifier/MemberActivityEventNotifier.java
- layer-external/src/main/java/org/layer/discord/notifier/SignUpEventNotifier.java
> [admin] feat: 작성 화면에서 머무는 평균 체류 시간 저장 로직 구현 (#380)

- layer-admin/src/main/java/org/layer/admin/retrospect/controller/AdminRetrospectController.java
- layer-admin/src/main/java/org/layer/admin/retrospect/controller/dto/RetrospectStayTimeResponse.java
- layer-admin/src/main/java/org/layer/admin/retrospect/entity/AdminRetrospectAnswerHistory.java
- layer-admin/src/main/java/org/layer/admin/retrospect/enums/AnswerTimeRange.java
- layer-admin/src/main/java/org/layer/admin/retrospect/repository/AdminRetrospectRepository.java
- layer-admin/src/main/java/org/layer/admin/retrospect/service/AdminRetrospectService.java
- layer-api/src/main/java/org/layer/global/exception/GlobalExceptionHandler.java
- 회고 작성 체류시간 조회 API를 개발했습니다.
- feat/
- closed #
> feat: 회고 작성 체류시간 조회

- layer-admin/src/main/java/org/layer/admin/space/service/AdminSpaceService.java
- 페이지 수 데이터가 잘못되어 수정했습니다.
- feat/
- closed #
> [admin[ fix: 페이지수 오류 해결

- layer-admin/src/main/java/org/layer/admin/space/entity/AdminMemberSpaceHistory.java
- layer-admin/src/main/java/org/layer/admin/space/listener/SpaceEventListener.java
- layer-admin/src/main/java/org/layer/admin/space/repository/AdminMemberSpaceRepository.java
- layer-admin/src/main/java/org/layer/admin/space/repository/AdminMemberSpaceRepositoryCustom.java
- layer-admin/src/main/java/org/layer/admin/space/repository/AdminMemberSpaceRepositoryImpl.java
- layer-admin/src/main/java/org/layer/admin/space/repository/AdminSpaceRepository.java
- layer-admin/src/main/java/org/layer/admin/space/service/AdminSpaceService.java
- layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
- layer-event/src/main/java/org/layer/event/space/JoinSpaceEvent.java
- layer-event/src/main/java/org/layer/event/space/LeaveSpaceEvent.java
- 스페이스가 기준이 아닌 스페이스와 멤버 사이의 중간테이블을 기준으로 팀스페이스 비율 집계했습니다.
- feat/
- closed #
> [admin] fix: 스페이스가 기준이 아닌 스페이스와 멤버 사이의 중간테이블을 기준으로 팀스페이스 비율 집계

- layer-admin/src/main/java/org/layer/admin/retrospect/controller/AdminRetrospectController.java
- layer-admin/src/main/java/org/layer/admin/retrospect/controller/dto/RetrospectCompletionRateResponse.java
- layer-admin/src/main/java/org/layer/admin/retrospect/repository/AdminRetrospectAnswerRepository.java
- layer-admin/src/main/java/org/layer/admin/retrospect/repository/dto/RetrospectAnswerCompletionDto.java
- layer-admin/src/main/java/org/layer/admin/retrospect/service/AdminRetrospectService.java
- 회고 완수율 조회 기능을 구현했습니다.
- feat/
- closed #402
> [admin] feat: 회고 완수율 조회 기능 구현

- layer-admin/src/main/java/org/layer/admin/space/service/AdminSpaceService.java
- layer-admin/src/main/java/org/layer/admin/template/service/AdminTemplateService.java
> fix: 데이터 수집 로직 수정

- layer-api/src/main/java/org/layer/aop/ExecutionLoggingAop.java
> del: 로깅 코드 제거

- layer-admin/src/main/java/org/layer/admin/member/entity/AdminMemberSignupHistory.java
- layer-admin/src/main/java/org/layer/admin/retrospect/entity/AdminRetrospectAnswerHistory.java
- layer-admin/src/main/java/org/layer/admin/retrospect/entity/AdminRetrospectHistory.java
- layer-admin/src/main/java/org/layer/admin/space/entity/AdminMemberSpaceHistory.java
- layer-admin/src/main/java/org/layer/admin/space/entity/AdminSpaceHistory.java
- layer-admin/src/main/java/org/layer/admin/template/controller/AdminTemplateController.java
- layer-admin/src/main/java/org/layer/admin/template/controller/dto/TemplateClickCountResponse.java
- layer-admin/src/main/java/org/layer/admin/template/entity/AdminTemplateChoice.java
- layer-admin/src/main/java/org/layer/admin/template/entity/AdminTemplateClickHistory.java
- layer-admin/src/main/java/org/layer/admin/template/listener/TemplateListViewEventListener.java
- layer-admin/src/main/java/org/layer/admin/template/listener/TemplateRecommendedEventListener.java
- layer-admin/src/main/java/org/layer/admin/template/repository/AdminTemplateChoiceRepository.java
- layer-admin/src/main/java/org/layer/admin/template/repository/AdminTemplateClickHistoryRepository.java
- layer-admin/src/main/java/org/layer/admin/template/service/AdminTemplateService.java
- layer-api/src/main/java/org/layer/domain/form/service/FormService.java
- layer-api/src/main/java/org/layer/domain/stats/StatsTemplateApi.java
- layer-api/src/main/java/org/layer/domain/stats/StatsTemplateController.java
- layer-event/src/main/java/org/layer/event/template/TemplateListViewChoiceEvent.java
- layer-event/src/main/java/org/layer/event/template/TemplateListViewClickEvent.java
- layer-event/src/main/java/org/layer/event/template/TemplateRecommendedChoiceEvent.java
- layer-event/src/main/java/org/layer/event/template/TemplateRecommendedClickEvent.java
- 혼재되고 있던 어드민 도메인 이름들을 정리했습니다.
- 오해를 줄이기 위해 주석을 추가했습니다.
- feat/
- closed #427
> [admin] refactor: 어드민 도메인 정리

- layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/response/RetrospectGetResponse.java
- layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
- spaceId 필드를 추가했습니다.
- feat/
- closed #
> chore: spaceId 추가
